import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/HomePage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marvel - Search Heros</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      </Head>
      <Card />
      <button className={styles.returnTop} onClick={(e) => window.scrollTo(0, 0)}>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" fill="white" className="bi bi-caret-up" viewBox="0 0 16 16">
  <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z"/>
</svg>
      </button>
      <footer className={styles.footer}>
        <p>Desenvolvido por: Raphael Caetano</p>
      </footer>
    </div>
  )
}
